-- Initial relational schema for the commerce-agent target database.
-- Primary keys use snowflake-style bigint ids generated by the application.

BEGIN;

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id BIGINT REFERENCES categories(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT PRIMARY KEY,
    sku TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    short_description TEXT NOT NULL,
    long_description TEXT NOT NULL DEFAULT '',
    brand TEXT,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    status TEXT NOT NULL DEFAULT 'active',
    attributes_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_media (
    id BIGINT PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    media_type TEXT NOT NULL DEFAULT 'image',
    url TEXT NOT NULL,
    thumbnail_url TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    alt_text TEXT,
    width INT,
    height INT,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS sellers (
    id BIGINT PRIMARY KEY,
    seller_code TEXT UNIQUE,
    name TEXT NOT NULL,
    rating NUMERIC(3, 2),
    seller_url TEXT,
    location TEXT,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_offers (
    id BIGINT PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    seller_id BIGINT NOT NULL REFERENCES sellers(id),
    price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    currency TEXT NOT NULL DEFAULT 'USD',
    inventory_count INT NOT NULL DEFAULT 0 CHECK (inventory_count >= 0),
    product_url TEXT NOT NULL,
    shipping_info TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_review_stats (
    product_id BIGINT PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
    average_rating NUMERIC(3, 2) CHECK (average_rating >= 0 AND average_rating <= 5),
    review_count INT NOT NULL DEFAULT 0 CHECK (review_count >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_search_documents (
    product_id BIGINT PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
    search_text TEXT NOT NULL,
    search_tsv TSVECTOR NOT NULL
);

CREATE TABLE IF NOT EXISTS product_embeddings (
    id BIGINT PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    embedding_type TEXT NOT NULL CHECK (embedding_type IN ('text', 'image', 'multimodal')),
    model_name TEXT NOT NULL,
    model_version TEXT,
    embedding VECTOR(2048) NOT NULL,
    source_text TEXT,
    source_image_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_embedding_variant
    ON product_embeddings(product_id, embedding_type, model_name);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_primary_media
    ON product_media(product_id)
    WHERE is_primary = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_active_offer_per_seller
    ON product_offers(product_id, seller_id)
    WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_categories_parent_id
    ON categories(parent_id);

CREATE INDEX IF NOT EXISTS idx_products_category_id
    ON products(category_id);

CREATE INDEX IF NOT EXISTS idx_products_status
    ON products(status);

CREATE INDEX IF NOT EXISTS idx_product_media_product_id
    ON product_media(product_id);

CREATE INDEX IF NOT EXISTS idx_product_offers_product_id
    ON product_offers(product_id);

CREATE INDEX IF NOT EXISTS idx_product_offers_seller_id
    ON product_offers(seller_id);

CREATE INDEX IF NOT EXISTS idx_product_offers_active_price
    ON product_offers(is_active, price);

CREATE INDEX IF NOT EXISTS idx_product_search_documents_tsv
    ON product_search_documents
    USING GIN(search_tsv);

CREATE INDEX IF NOT EXISTS idx_product_search_documents_text_trgm
    ON product_search_documents
    USING GIN(search_text gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_product_embeddings_product_id
    ON product_embeddings(product_id);

CREATE INDEX IF NOT EXISTS idx_product_embeddings_type
    ON product_embeddings(embedding_type);

-- Keep vector indexes out of the default 2048-d schema for now.
-- pgvector HNSW indexes reject dimensions above 2000, and the local
-- development dataset is still small enough for direct vector scans.

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_sellers_updated_at ON sellers;
CREATE TRIGGER trg_sellers_updated_at
BEFORE UPDATE ON sellers
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;
